# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/images', verbose_name='Imagem'),
        ),
    ]
