# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-12 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170112_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, verbose_name='Atalho'),
            preserve_default=False,
        ),
    ]
