# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-12 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbaPrincipal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nome')),
                ('link', models.CharField(max_length=50, verbose_name='link')),
                ('is_active', models.BooleanField(verbose_name='Está ativo?')),
                ('compost', models.BooleanField(verbose_name='É composto?')),
            ],
        ),
    ]
